### ISSUE TITLE
TypeError from hooks.py

### ISSUE THREAD

**Issue by dtchang** [jimfleming/recurrent-entity-networks#10]
File "C:\AI\Code\- EntNet\flemming\entity_networks\hooks.py", line 58, in after_run
    (not self._minimize and current_value > self._best_value) or \

TypeError: '>' not supported between instances of 'float' and 'NoneType'

**Comment by liuny05** [comment]
This is because the value of `self._best_value` is `None` at the beginning. So it can't be compared.
Simply change the order of the conditions in hooks.py, line 58 can solve this.
For example, you can change
```python
if (self._minimize and current_value < self._best_value) or \
   (not self._minimize and current_value > self._best_value) or \
   (self._best_value is None):
```
to
```python
if (self._best_value is None) or \
   (self._minimize and current_value < self._best_value) or \
   (not self._minimize and current_value > self._best_value):
```

**Comment by SeekPoint** [comment]
I got the same idea

**Comment by jimfleming** [comment]
Weird. I'm not sure how that ever worked. I've updated the code to reflect @liuny05's suggestion.
