### ISSUE TITLE
what's the create_instances.py used for?

### ISSUE THREAD

**Issue by SeekPoint** [jimfleming/recurrent-entity-networks#11]

**Comment by jimfleming** [comment]
This script converts many of the task questions to JSON payloads as expected by our deployed inference model: http://fomoro.com/demo/story-time/

It probably doesn't belong in this repo but I don't have a better place for it atm.

EDIT: More details:

1. We deploy a pre-trained model to GCP for inference.
2. We convert many of the test-time questions to JSON.
3. We identify the "actors" in each story to generate questions.
4. These questions are fed to the model via an API: https://cloud.google.com/ml-engine/docs/how-tos/online-predict
