### ISSUE TITLE
path issue ( download_babi.sh / prep.py )

### ISSUE THREAD

**Issue by dongheechoi** [jimfleming/recurrent-entity-networks#12]
When I executed "download_babi.sh", there's 'datasets/babi_tasks_data_1_20_v1.2.tar.gz'
But, after then, when I executed ' - python3.5 ./entity_networks/prep_data.py

There's error log like this.
->
FileNotFoundError: [Errno 2] No such file or directory: 'data/babi_tasks_data_1_20_v1.2.tar.gz'

I think they should be synced.

**Comment by dtchang** [comment]
This issue is closed. Please see Comment on Issue #9.

**Comment by jimfleming** [comment]
Missed a place where the path had been updated. Latest version should work? :)
