### ISSUE TITLE
Main throws error ( arg error ) & Data path problem

### ISSUE THREAD

**Issue by dongheechoi** [jimfleming/recurrent-entity-networks#13]
$python3.5 -m entity_networks.main

usage: main.py [-h] [--data-dir DATA_DIR] --dataset-id DATASET_ID --job-dir
               JOB_DIR [--num-epochs NUM_EPOCHS] [--lr-min LR_MIN]
               [--lr-max LR_MAX] [--lr-step-size LR_STEP_SIZE]
               [--grad-noise GRAD_NOISE]
main.py: error: the following arguments are required: --dataset-id, --job-dir

I found the explanation about 'dataset-id' based on your code, then I used
"python3.5 -m entity_networks.main --dataset-id qa1 --job-dir qa1"

But, again, there's a path error, so I moved ./data/records into ./data/babi/records.
And then it worked!

**Comment by dtchang** [comment]
I got the same path error and had to make the same manual move.

**Comment by lxtGH** [comment]
I got the same path error as well

**Comment by IrvingBei** [comment]
我也遇到了相同的错误，然后我这样修改后就可以执行了：
1：进入entity_networks目录，运行download_babi.sh，然后再运行prep_data.py ；
2：在entity_networks/data目录下新建babi文件夹，将records文件夹移进babi文件夹里；
3：将entity_networks目录下的data文件夹移动到recurrent-entity-networks目录下；
4：在recurrent-entity-networks目录下命令行执行“python -m entity_networks.main --dataset-id qa1 --job-dir qa1”
这样就可以运行了！

I also encountered the same error, and then I modified it :
1: enter the `entity_networks` directory, run `download_babi.sh`, and then run `prep_data.py`;
2: create a new `babi` folder in the `entity_networks/data` directory and move the `records` folder into the `babi` folder;
3. Move the `data` folder in the directory of `entity_networks` to the directory of `recurrent-entity-networks`;
4: In `recurrent-entity-networks` folder ,the command line executes `python-m entity_net.main --dataset-id qa1 --job-dir qa1`;
This will run!
