### ISSUE TITLE
retains previous state

### ISSUE THREAD

**Issue by indiejoseph** [jimfleming/recurrent-entity-networks#6]
Is it possible to feed the previous `last_state` as `initial_state` for dynamic memory cell to retains previous story memory?

**Comment by jimfleming** [comment]
The call to `dynamic_rnn` (https://github.com/jimfleming/recurrent-entity-networks/blob/master/entity_networks/model.py#L59) handles this automatically. The `last_state` tensor isn't the value itself but a node for the actual value to pass through.
