### ISSUE TITLE
Why initialize value with its key?

### ISSUE THREAD

**Issue by subercui** [jimfleming/recurrent-entity-networks#7]
It seems in your code `dynamic_memory_cell.py`,  value is initialized with its respect key. It is kind of rare and I am curious why doing this.
```  python
 def zero_state(self, batch_size, dtype):
        """
        We initialize the memory to the key values.
        """
        zero_state = tf.concat(1, [tf.expand_dims(key, 0) for key in self._keys])
        zero_state_batch = tf.tile(zero_state, tf.pack([batch_size, 1]))
        return zero_state_batch
```
Does this come from the paper? or for some specific purpose?

**Comment by jimfleming** [comment]
It's from the paper in Appendix A:

> The initial values of the memory slots were initialized to the key values, which we found to help performance.

This conditions the memory on matching keys.
